// Representative excerpt from a real Flow Contents report — anonymized "Sample Property"
// (based on Strum, 5,032 items / $502K total). Used for the in-modal spreadsheet preview.
//
// TODO: replace with a fuller export pulled directly from the platform
// (flow-contents-platform/functions/src/report/) once the canonical sample property
// is finalized. For now this is a curated slice that shows the field shape across rooms.

export interface SampleRow {
  room: string
  name: string
  description: string
  features: string
  category: string
  xactCode: string
  age: string
  condition: string
  acv: number
  rcv: number
  link: { vendor: string; url: string }
}

export const sampleRows: SampleRow[] = [
  // ── Living Room ────────────────────────────────────────
  {
    room: "Living Room",
    name: "Sectional Sofa",
    description: "Top-grain leather sectional, 3-piece L-shape",
    features: "Natuzzi Italia 'Amalfi', 8-way hand-tied, aniline leather",
    category: "Furniture",
    xactCode: "FRN SOFA-LR+",
    age: "4 yrs",
    condition: "Good",
    acv: 3744.0,
    rcv: 6240.0,
    link: { vendor: "Natuzzi", url: "https://www.natuzzi.com/" },
  },
  {
    room: "Living Room",
    name: "Persian-Style Area Rug",
    description: "Hand-knotted wool, oriental medallion pattern, 9'×12'",
    features: "Wool pile, cotton foundation, traditional motif",
    category: "Floor Covering",
    xactCode: "FRN RUG-PER",
    age: "10 yrs",
    condition: "Fair",
    acv: 1092.0,
    rcv: 1820.0,
    link: { vendor: "Wayfair", url: "https://www.wayfair.com/" },
  },
  {
    room: "Living Room",
    name: "Tufted Velvet Accent Chair",
    description: "Button-tufted velvet wingback, blush",
    features: "Cabriole legs, curved arms, deep button tufting",
    category: "Furniture",
    xactCode: "FRN CHR-ACC",
    age: "2 yrs",
    condition: "Excellent",
    acv: 510.0,
    rcv: 680.0,
    link: { vendor: "West Elm", url: "https://www.westelm.com/" },
  },
  {
    room: "Living Room",
    name: "Dark Wood Coffee Table",
    description: "Two-tier rectangular coffee table",
    features: "Carved legs, dark walnut finish, lower display shelf",
    category: "Furniture",
    xactCode: "FRN TBL-COF",
    age: "6 yrs",
    condition: "Good",
    acv: 280.0,
    rcv: 560.0,
    link: { vendor: "Pottery Barn", url: "https://www.potterybarn.com/" },
  },
  {
    room: "Living Room",
    name: "Brass Floor Lamp",
    description: "Tripod brass floor lamp with linen drum shade",
    features: "Adjustable height, brushed brass finish",
    category: "Lighting",
    xactCode: "LIT FLR-LMP",
    age: "3 yrs",
    condition: "Good",
    acv: 178.0,
    rcv: 295.0,
    link: { vendor: "CB2", url: "https://www.cb2.com/" },
  },

  // ── Kitchen ────────────────────────────────────────────
  {
    room: "Kitchen",
    name: "Smart Toaster, 4-slice",
    description: "Stainless steel 4-slice toaster with LCD",
    features: "Breville BTA840XL, lift-and-look, A-bit-more button",
    category: "Small Appliance",
    xactCode: "KIT TOAS+",
    age: "3 yrs",
    condition: "Good",
    acv: 89.4,
    rcv: 149.95,
    link: {
      vendor: "Williams Sonoma",
      url: "https://www.williams-sonoma.com/products/breville-smart-toaster/",
    },
  },
  {
    room: "Kitchen",
    name: "Espresso Machine, semi-automatic",
    description: "Semi-automatic espresso machine with steam wand",
    features: "Breville Barista Express, built-in conical burr grinder",
    category: "Small Appliance",
    xactCode: "KIT ESP+",
    age: "2 yrs",
    condition: "Excellent",
    acv: 597.0,
    rcv: 749.95,
    link: { vendor: "Sur La Table", url: "https://www.surlatable.com/" },
  },
  {
    room: "Kitchen",
    name: "Stand Mixer, 5-quart",
    description: "Tilt-head stand mixer, empire red",
    features: "KitchenAid Artisan KSM150PSER, 10-speed",
    category: "Small Appliance",
    xactCode: "KIT MIX-STD",
    age: "5 yrs",
    condition: "Good",
    acv: 264.0,
    rcv: 449.99,
    link: { vendor: "KitchenAid", url: "https://www.kitchenaid.com/" },
  },
  {
    room: "Kitchen",
    name: "Stainless Cookware Set, 10-piece",
    description: "Tri-ply stainless steel cookware set",
    features: "All-Clad D3, induction-compatible, lifetime warranty",
    category: "Cookware",
    xactCode: "KIT COOK-SET",
    age: "7 yrs",
    condition: "Good",
    acv: 580.0,
    rcv: 1199.95,
    link: { vendor: "All-Clad", url: "https://www.all-clad.com/" },
  },
  {
    room: "Kitchen",
    name: "Chef's Knife, 8-inch",
    description: "Forged 8-inch chef's knife, German steel",
    features: "Wüsthof Classic, full tang, triple-riveted handle",
    category: "Cutlery",
    xactCode: "KIT KNF-CHF",
    age: "8 yrs",
    condition: "Good",
    acv: 89.0,
    rcv: 169.95,
    link: { vendor: "Wüsthof", url: "https://www.wusthof.com/" },
  },

  // ── Primary Bedroom ────────────────────────────────────
  {
    room: "Primary Bedroom",
    name: "Upholstered King Bed Frame",
    description: "Linen upholstered king platform bed",
    features: "Pottery Barn 'Raleigh', wing-style headboard, oatmeal linen",
    category: "Furniture",
    xactCode: "FRN BED-KNG",
    age: "5 yrs",
    condition: "Good",
    acv: 1199.0,
    rcv: 1999.0,
    link: { vendor: "Pottery Barn", url: "https://www.potterybarn.com/" },
  },
  {
    room: "Primary Bedroom",
    name: "Memory Foam Mattress, King",
    description: "12-inch hybrid memory foam mattress, king",
    features: "Casper Original Hybrid, zoned support, breathable cover",
    category: "Mattress",
    xactCode: "FRN MAT-KNG",
    age: "3 yrs",
    condition: "Good",
    acv: 1395.0,
    rcv: 1995.0,
    link: { vendor: "Casper", url: "https://casper.com/" },
  },
  {
    room: "Primary Bedroom",
    name: "Walnut 6-Drawer Dresser",
    description: "Mid-century walnut 6-drawer wide dresser",
    features: "Solid walnut, hairpin legs, soft-close drawers",
    category: "Furniture",
    xactCode: "FRN DRS-6D",
    age: "4 yrs",
    condition: "Excellent",
    acv: 1199.0,
    rcv: 1599.0,
    link: { vendor: "Article", url: "https://www.article.com/" },
  },
  {
    room: "Primary Bedroom",
    name: "Egyptian Cotton Sheet Set, King",
    description: "1000-thread-count Egyptian cotton sheet set, king",
    features: "Sateen weave, deep pocket fitted sheet, 4-piece",
    category: "Linens",
    xactCode: "BED SHT-KNG",
    age: "2 yrs",
    condition: "Good",
    acv: 159.0,
    rcv: 265.0,
    link: { vendor: "Brooklinen", url: "https://www.brooklinen.com/" },
  },

  // ── Home Office ────────────────────────────────────────
  {
    room: "Home Office",
    name: "Roll-Top Secretary Desk",
    description: "Antique wooden roll-top secretary desk",
    features: "Three drawers, cubby compartments, turned legs",
    category: "Furniture",
    xactCode: "FRN DSK-RT",
    age: "20 yrs",
    condition: "Good",
    acv: 680.0,
    rcv: 1360.0,
    link: { vendor: "1stDibs", url: "https://www.1stdibs.com/" },
  },
  {
    room: "Home Office",
    name: "Ergonomic Task Chair",
    description: "High-back mesh task chair with lumbar support",
    features: "Herman Miller Aeron, size B, fully adjustable",
    category: "Furniture",
    xactCode: "FRN CHR-OFF",
    age: "6 yrs",
    condition: "Good",
    acv: 875.0,
    rcv: 1745.0,
    link: { vendor: "Herman Miller", url: "https://www.hermanmiller.com/" },
  },
  {
    room: "Home Office",
    name: "Atlas of Ancient Indian History",
    description: "Hardback scholarly reference text",
    features: "Green cloth cover, dust jacket, 380 pages",
    category: "Books",
    xactCode: "BOK HC-REF",
    age: "8 yrs",
    condition: "Good",
    acv: 28.8,
    rcv: 48.0,
    link: { vendor: "AbeBooks", url: "https://www.abebooks.com/" },
  },
  {
    room: "Home Office",
    name: "Mesh Desk Organizer, 5-section",
    description: "Powder-coated steel mesh desk organizer",
    features: "Safco Onyx, 5 sections, side handles",
    category: "Office Supplies",
    xactCode: "OFF ORG-DSK",
    age: "5 yrs",
    condition: "Good",
    acv: 24.0,
    rcv: 42.0,
    link: { vendor: "Office Depot", url: "https://www.officedepot.com/" },
  },

  // ── Exercise Room ──────────────────────────────────────
  {
    room: "Exercise Room",
    name: "Treadmill, Folding",
    description: "Folding treadmill with 10-inch HD touchscreen",
    features: "NordicTrack Commercial 1750, 12% incline, iFit-enabled",
    category: "Exercise Equipment",
    xactCode: "REC EX-TRD",
    age: "3 yrs",
    condition: "Good",
    acv: 1499.0,
    rcv: 2499.0,
    link: { vendor: "NordicTrack", url: "https://www.nordictrack.com/" },
  },
  {
    room: "Exercise Room",
    name: "Adjustable Dumbbells, pair",
    description: "Adjustable dumbbells 5–52.5 lb, pair",
    features: "Bowflex SelectTech 552, dial-a-weight system",
    category: "Exercise Equipment",
    xactCode: "REC EX-DMB",
    age: "4 yrs",
    condition: "Good",
    acv: 269.0,
    rcv: 449.0,
    link: { vendor: "Bowflex", url: "https://www.bowflex.com/" },
  },
  {
    room: "Exercise Room",
    name: "Yoga Mat, premium",
    description: "Natural rubber yoga mat with alignment markers",
    features: "Manduka PRO, 6mm, lifetime warranty",
    category: "Exercise Equipment",
    xactCode: "REC EX-YOG",
    age: "3 yrs",
    condition: "Good",
    acv: 84.0,
    rcv: 138.0,
    link: { vendor: "Manduka", url: "https://www.manduka.com/" },
  },

  // ── Garage ─────────────────────────────────────────────
  {
    room: "Garage",
    name: "Cordless Drill, 20V",
    description: "20V brushless cordless drill/driver kit",
    features: "DeWalt DCD791, 2 batteries, charger, hard case",
    category: "Power Tools",
    xactCode: "TOO POW-DRL",
    age: "5 yrs",
    condition: "Good",
    acv: 119.0,
    rcv: 199.0,
    link: { vendor: "Home Depot", url: "https://www.homedepot.com/" },
  },
  {
    room: "Garage",
    name: "Rolling Tool Chest, 41-inch",
    description: "41-inch 6-drawer rolling tool chest, red",
    features: "Husky industrial-grade, ball-bearing slides, locking",
    category: "Storage",
    xactCode: "TOO STR-CHT",
    age: "8 yrs",
    condition: "Good",
    acv: 348.0,
    rcv: 580.0,
    link: { vendor: "Home Depot", url: "https://www.homedepot.com/" },
  },
  {
    room: "Garage",
    name: "Pressure Washer, electric",
    description: "Electric pressure washer, 2030 PSI",
    features: "Sun Joe SPX3000, dual detergent tanks, 5 quick-connect tips",
    category: "Outdoor Equipment",
    xactCode: "OUT EQU-PWR",
    age: "4 yrs",
    condition: "Good",
    acv: 119.0,
    rcv: 199.0,
    link: { vendor: "Amazon", url: "https://www.amazon.com/" },
  },

  // ── Exterior ───────────────────────────────────────────
  {
    room: "Exterior",
    name: "Patio Dining Set, 6-seat",
    description: "Teak outdoor dining set, table + 6 chairs",
    features: "Solid teak, weatherproof, expandable to 8",
    category: "Outdoor Furniture",
    xactCode: "OUT FRN-DIN",
    age: "5 yrs",
    condition: "Fair",
    acv: 2099.0,
    rcv: 3499.0,
    link: { vendor: "Pottery Barn", url: "https://www.potterybarn.com/" },
  },
  {
    room: "Exterior",
    name: "Gas Grill, 4-burner",
    description: "Stainless 4-burner natural gas grill with side burner",
    features: "Weber Genesis II E-435, GS4 grilling system",
    category: "Outdoor Equipment",
    xactCode: "OUT EQU-GRL",
    age: "4 yrs",
    condition: "Good",
    acv: 599.0,
    rcv: 999.0,
    link: { vendor: "Weber", url: "https://www.weber.com/" },
  },
  {
    room: "Exterior",
    name: "Outdoor Lounge Set, 4-pc",
    description: "Wicker outdoor lounge set with cushions, 4-pc",
    features: "Powder-coated frame, all-weather wicker, Sunbrella cushions",
    category: "Outdoor Furniture",
    xactCode: "OUT FRN-LNG",
    age: "3 yrs",
    condition: "Good",
    acv: 999.0,
    rcv: 1799.0,
    link: { vendor: "Wayfair", url: "https://www.wayfair.com/" },
  },

  // ── Hall Bathroom ──────────────────────────────────────
  {
    room: "Hall Bathroom",
    name: "Egyptian Cotton Bath Towel Set",
    description: "8-piece Egyptian cotton bath towel set",
    features: "700 GSM, hotel-grade, plush long-staple cotton",
    category: "Linens",
    xactCode: "BTH TWL-SET",
    age: "2 yrs",
    condition: "Good",
    acv: 89.0,
    rcv: 149.0,
    link: { vendor: "Brooklinen", url: "https://www.brooklinen.com/" },
  },
  {
    room: "Hall Bathroom",
    name: "Electric Toothbrush, sonic",
    description: "Sonic electric toothbrush with travel case",
    features: "Philips Sonicare DiamondClean 9000, 4 modes",
    category: "Personal Care",
    xactCode: "BTH TBR-ELE",
    age: "1 yr",
    condition: "Excellent",
    acv: 165.0,
    rcv: 219.95,
    link: { vendor: "Philips", url: "https://www.usa.philips.com/" },
  },
]
